import { type GetServerSidePropsContext } from "next";
import { getSession } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/router";

import { Drawer } from "~/components/Drawer";
import { AreaLineChart } from "~/components/charts/AreaLineChart";
import { TradeCalendar } from "~/features/tradeCalendar";
import {
  DateRangeButton,
  DateRangeSchema,
  generateDateRangeUrl,
} from "~/features/tradeHistory";
import { TagStats, TradePnlStats } from "~/features/tradeStats";

export default function Home() {
  const router = useRouter();

  const handleDateChange = (dates: unknown) => {
    const currentUrl = router.pathname;
    const [start, end] = DateRangeSchema.parse(dates);

    const newUrl = generateDateRangeUrl(currentUrl, start, end);

    void router.replace(newUrl, undefined, { shallow: true });
  };

  return (
    <>
      <Head>
        <title>Trade-CoPilot</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Drawer>
          <div className="flex min-h-screen flex-col p-10">
            <div className="relative my-3 flex self-end">
              <DateRangeButton passDateChange={handleDateChange} />
            </div>
            <div className="lg:flex lg:justify-between">
              <div className="hidden lg:block">
                <TagStats />
                <AreaLineChart />
              </div>
              <div className="flex flex-col">
                <div className="mb-4">
                  <TradePnlStats />
                </div>
                <div className="mb-4 text-center">
                  <TradeCalendar />
                </div>
              </div>
            </div>
          </div>
        </Drawer>
      </main>
    </>
  );
}

export async function getServerSideProps({ req }: GetServerSidePropsContext) {
  const session = await getSession({ req });

  if (!session) {
    return {
      redirect: {
        destination: "/login",
        permanent: false,
      },
    };
  }

  return {
    props: { session },
  };
}
