import { type GetServerSidePropsContext } from "next";
import { getSession } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/router";

import { Drawer } from "~/components/auth/Drawer";
import { AreaLineChart } from "~/components/charts/AreaLineChart";
import { AppleCardsCarouselDemo } from "~/components/ui/AppleCardDemo";
import DailyTradeCarousel from "~/components/ui/DailyTradeCarousel";
import { TradeCalendar } from "~/features/tradeCalendar";
import {
  DateRangeButton,
  DateRangeSchema,
  generateDateRangeUrl,
} from "~/features/tradeHistory";
import { TagStats, TradePnlStats } from "~/features/tradeStats";

export default function Home() {
  const router = useRouter();

  const handleDateChange = (dates: unknown) => {
    const currentUrl = router.pathname;
    const [start, end] = DateRangeSchema.parse(dates);

    const newUrl = generateDateRangeUrl(currentUrl, start, end);

    void router.replace(newUrl, undefined, { shallow: true });
  };

  return (
    <>
      <Head>
        <title>Trade-CoPilot</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* <Drawer> */}
        {/* <AppleCardsCarouselDemo /> */}

        {/* <TradeCalendar /> */}

        {/* <AreaLineChart /> */}

        {/* <TradePnlStats /> */}
        {/* <AppleCardsCarouselDemo /> */}
        {/* <DailyTradeCarousel /> */}
        <Drawer>
          <div className="flex min-h-screen flex-col p-10">
            <div className="relative my-3 flex self-end">
              <DateRangeButton passDateChange={handleDateChange} />
            </div>
            <div className="lg:flex lg:justify-between">
              <div className="hidden lg:block">
                <TagStats />
                <AreaLineChart />
              </div>
              <div className="flex flex-col">
                <div className="mb-4">
                  <TradePnlStats />
                </div>
                <div className="mb-4 text-center">
                  <TradeCalendar />
                </div>
              </div>
            </div>
          </div>
        </Drawer>
        {/* </Drawer> */}
        {/* <div className="btm-nav">
          <button>
            <svg
              xmlns="http://www.w3.org/2000/svg"
              className="h-5 w-5"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth="2"
                d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6"
              />
            </svg>
          </button>
          <button className="active">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              className="h-5 w-5"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth="2"
                d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
              />
            </svg>
          </button>
          <button>
            <svg
              xmlns="http://www.w3.org/2000/svg"
              className="h-5 w-5"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth="2"
                d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z"
              />
            </svg>
          </button>
        </div> */}
      </main>
    </>
  );
}

export async function getServerSideProps({ req }: GetServerSidePropsContext) {
  const session = await getSession({ req });

  if (!session) {
    return {
      redirect: {
        destination: "/login",
        permanent: false,
      },
    };
  }

  return {
    props: { session },
  };
}
